---
- name: using register and debug
  hosts: worker
  tasks:
  - name: ping
    ping: 
    register: ping_result
  - name: display result
    debug:
     msg: "the result of ping is {{ ping_result['ping'] }}"
...
