---
- name: using register and debug
  hosts: worker
  tasks: 
  - name: echo command on shell
    shell:
     cmd: echo item number {{ item }}
    loop:
    - one
    - two
    - three
    register: echo_result
  - name: dispaly result
    debug: 
     msg: "{{ item.stdout }}"
    loop: "{{ echo_result['results'] }}"
...
