---
- name: create user
  hosts: worker
  vars_files:
  - users.yaml                                                                                                                       
  tasks:
  - name: create user {{ user }}
    user:
     name: "{{ user }}"
...
